version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      # 请根据实际需求修改密码和数据库名
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - doctranslator-mysql:/var/lib/mysql
    networks: 
      - my-network

  backend:
    image: doctranslator
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key
      # 数据库配置（开发/生产环境均使用 MySQL）
      # 原：SQLALCHEMY_DATABASE_URI=sqlite:////app/db/dev.db
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:password@mysql:3306/appdb
      # 原：DEV_DATABASE_URL=sqlite:////app/db/dev.db
      - DEV_DATABASE_URL=mysql+pymysql://user:password@mysql:3306/appdb
      # 原：PROD_DATABASE_URL=sqlite:////app/db/dev.db
      - PROD_DATABASE_URL=mysql+pymysql://user:password@mysql:3306/appdb

      - JWT_SECRET_KEY=sxxxxxx
      - JWT_ACCESS_TOKEN_EXPIRES=172800
      # 邮件配置
      - MAIL_SERVER=smtp.qq.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=xxxx@qq.com
      - MAIL_PASSWORD=xxxxxx
      - MAIL_DEFAULT_SENDER=ixxxx@qq.com
      - ALLOWED_EMAIL_DOMAINS=qq.com,163.com,126.com
      # 跨域 允许的域名
      - ALLOWED_DOMAINS=*
    depends_on:
      - mysql
    networks:
      - my-network

  # ... existing code ...
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "1475:80"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html/frontend
      - ./admin/dist:/usr/share/nginx/html/admin
    depends_on:
      - backend
    networks:
      - my-network

volumes:
  doctranslator-mysql:

networks:
  my-network:
    driver: bridge
